#!/usr/bin/env bash

install() {
  local dir="${XDG_CONFIG_HOME:-$HOME/.config}"
  link "$REPOSITORY_ROOT" "$dir/Code/User"
  link "$REPOSITORY_ROOT" "$dir/Code - OSS/User"
}

source <(curl -Lfs https://git.io/lnkr)
